medida = float(input('Uma distância em metros: '))
print('A medida de {}m corresponde a' .format(medida))
print('{}km' .format(medida / 1000))
print('{}hm' .format(medida / 100))
print('{}dam' .format(medida /10))
print('{}dm' .format(int(medida * 10)))
print('{}cm' .format(int(medida * 100)))
print('{}mm' .format(int(medida * 1000)))
